name: Merge Main to Feature Branches

on:
  push:
    branches:
      - main

jobs:
  merge-to-feature:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Necessary to fetch all branches
        token: ${{ secrets.ACCESS_TOKEN }} # Use the secret token for checkout

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Merge Main into Feature Branch
      run: |
        # Replace 'your-feature-branch-name' with your actual feature branch name
        FEATURE_BRANCH="test"
        git fetch origin
        git checkout $FEATURE_BRANCH
        git merge origin/main --no-edit
        # Use the secret token for pushing changes
        git push https://${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }} $FEATURE_BRANCH
