name: Create PR from Main to Feature Branches

on:
  push:
    branches:
      - main

jobs:
  create-pr-to-feature:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Necessary to fetch all branches
        token: ${{ secrets.TOKEN }} # Use the secret token for checkout

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Create New Branch for PR
      run: |
        PR_BRANCH="update-from-main-$(date +%Y%m%d%H%M%S)" # Unique branch name for the PR
        git checkout -b $PR_BRANCH
        git pull origin main

    - name: Push Changes to New Branch
      run: git push origin $PR_BRANCH
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.TOKEN }}
        branch: ${{ env.PR_BRANCH }} # The branch you've just pushed
        title: "Merge main into feature branch"
        body: "Automated PR to merge main changes into the feature branch."
        base: "your-feature-branch-name" # The target branch for the PR
        labels: "automerge" # Optional: Assign labels to the PR
