name: Auto PR from Main to Feature Branch

on:
  push:
    branches:
      - main

jobs:
  setup-and-create-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags
        token: ${{ secrets.TOKEN }} # Use the PAT for checkout

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Create New Branch for PR
      run: |
        PR_BRANCH="update-from-main-$(date +%Y%m%d%H%M%S)" # Generate a unique branch name
        git checkout -b $PR_BRANCH
        git pull origin main

    - name: Push New Branch
      run: git push -u origin $PR_BRANCH --all
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.TOKEN }}
        branch: $PR_BRANCH
        title: "Merge main into feature branch"
        body: "Automated PR to merge main changes into the feature branch."
        base: "test" # Specify your feature branch name here
        labels: "automerge" # Optional: Assign labels to the PR
