name: Merge Main to Feature Branches

on:
  push:
    branches:
      - qa-main

jobs:
  merge-to-feature:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Necessary to fetch all branches
        token: ${{ secrets.TOKEN }} # Use the secret token for checkout

    - name: Configure Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Merge Main into Feature Branches
      run: |
        git fetch origin
        # List all branches that start with env/, stripping the remote part
        for branch in $(git branch -r | grep 'origin/env/' | sed 's|origin/||'); do
          echo "Merging changes into $branch"
          git checkout $branch
          git merge origin/qa-main --no-edit
          # Push the changes using the secret token
          git push https://${{ secrets.TOKEN }}@github.com/${{ github.repository }} $branch
        done
